### ISSUE TITLE
Typo in the lab0 setup instruction 

### ISSUE THREAD

**Issue by kanlip** [edsml-kl121/compact-watsonx-ai-incubation-program#3]
<img width="437" alt="image" src="https://github.com/user-attachments/assets/e6186615-fe12-4782-9757-a69a06c6165e">

-  Adding PEM file instruction (6.)  'Go to this lab 06 directory' should be 'Go to this lab 04 directory' 
<img width="918" alt="image" src="https://github.com/user-attachments/assets/a1a009ab-2204-4ded-8b96-f62f12a1aad3">

- 'Cloning this Watsonx.ai workshop repo' link does not work
<img width="919" alt="image" src="https://github.com/user-attachments/assets/0fcf8473-ecaa-4a23-897f-a4afa38e4e05">

**Comment by tanyaaton** [comment]
resolved, new instruction is pushed
